-- Generated by Oracle SQL Developer Data Modeler Version: 2.0.0 Build: 584
--   at:        2011-11-30 15:38:30
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



CREATE TABLE downloads 
    ( 
     id_user NUMBER , 
     id_file NUMBER , 
     dldate NUMBER 
    ) 
;




CREATE TABLE files 
    ( 
     name VARCHAR2 (50)  NOT NULL , 
     type VARCHAR2 (20)  NOT NULL , 
     filesize NUMBER  NOT NULL , 
     path VARCHAR2 (100)  NOT NULL , 
     id_user NUMBER , 
     id_file NUMBER  NOT NULL , 
     timestamp NUMBER , 
     downloads NUMBER , 
     description VARCHAR2 (100) 
    ) 
;



ALTER TABLE files 
    ADD CONSTRAINT files_PK PRIMARY KEY ( id_file ) ;


CREATE TABLE subscription 
    ( 
     subdate NUMBER , 
     id_sub NUMBER , 
     id_user NUMBER 
    ) 
;




CREATE TABLE users 
    ( 
     id_user NUMBER  NOT NULL , 
     callsign VARCHAR2 (20)  NOT NULL , 
     password VARCHAR2 (40)  NOT NULL , 
     lastname VARCHAR2 (50)  NOT NULL , 
     firstname VARCHAR2 (50)  NOT NULL , 
     mail VARCHAR2 (30)  NOT NULL , 
     adress VARCHAR2 (200) , 
     creditcard NUMBER , 
     type NUMBER  NOT NULL 
    ) 
;



ALTER TABLE users 
    ADD CONSTRAINT users_PK PRIMARY KEY ( id_user ) ;



ALTER TABLE files 
    ADD CONSTRAINT Relation_4 FOREIGN KEY 
    ( 
     id_user
    ) 
    REFERENCES users 
    ( 
     id_user
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE subscription 
    ADD CONSTRAINT Relation_5 FOREIGN KEY 
    ( 
     id_user
    ) 
    REFERENCES users 
    ( 
     id_user
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE downloads 
    ADD CONSTRAINT Relation_6 FOREIGN KEY 
    ( 
     id_user
    ) 
    REFERENCES users 
    ( 
     id_user
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE downloads 
    ADD CONSTRAINT Relation_7 FOREIGN KEY 
    ( 
     id_file
    ) 
    REFERENCES files 
    ( 
     id_file
    ) 
    ON DELETE SET NULL 
;


    
    
    
    

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              6
-- CREATE VIEW                              0
-- CREATE PROCEDURE                         0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE SNAPSHOT                          0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
